name: Testing Self Hosted Runner

on: pull_request

jobs:
  hello:
    runs-on: [self-hosted, linux]
    steps:
      - name: Say Hello
        run: echo "Hello"
      - name: Print Secret
        run: echo ${{ secrets.PASSWORD }}
